### ISSUE TITLE
Autoprefixer status?

### ISSUE THREAD

**Issue by SachaG** [fourseven/meteor-scss#147]
What's the status on getting Autoprefixer to work again? Should I just give up on it and go back to using Compass mixins?

**Comment by sebakerckhof** [comment]
Well, seeing the post of david glasser here: https://github.com/meteor/meteor/issues/5219 , I assume autoprefixing won't be able to have it's own plugin anytime soon.

I'm also a bit reluctant to put it in here, since well, it's not a part of sass and this plugin used to support too many non-sass stuff, which now people expect to continue to work.
That being said, Autoprefixing is quite popular and it would probably not be too hard to include in this plugin. But I'd rather not publish it for the reasons above, but just create a separate branch which you can  clone in your local packages?

**Comment by SachaG** [comment]
If you're able to include it as part of this package, can't you somehow break off that part of the package as its own package? I'm asking because all Telescope sites are now completely broken in Safari. So it's kind of a big problem for me…

**Comment by derwaldgeist** [comment]
+1 for having the auto-prefixer as a separate package again. My app's styles are now broken as well, since I relied on auto-prefixing.

**Comment by sebakerckhof** [comment]
I'll create a separate release with autoprefixer enabled.

**Comment by SachaG** [comment]
Awesome!

**Comment by pixelass** [comment]
+1 

not a friend of having it tied to this package but we need a solution

**Comment by francisbyrne** [comment]
+1 We're really keen to upgrade to v1.2 but this is a blocking change. 
Let me know if you need any help getting this done @sebakerckhof :)

**Comment by sebakerckhof** [comment]
After some dicussion, I decided to leave it out of this package, but instead create a minifier package that includes autoprefixing. That will prevent every compiler (less, stylus, sass, ...) from having to implement this functionality over and over and it will also allow you to autoprefix normal css files from other packages (which is usually what you want to do anyway).

I hope I can find some time for it by the end of the week.

**Comment by SachaG** [comment]
Awesome, thanks so much for this! It's a huge life-saver :)

**Comment by derwaldgeist** [comment]
Thanks!

**Comment by sebakerckhof** [comment]
Can you guys test this package locally (instead of standard-minifiers):
https://github.com/sebakerckhof/meteor-minifiers-autoprefix

**Comment by pixelass** [comment]
@sebakerckhof how do I add it?

clone into packages?
`meteor ad ???:???`

**Comment by sebakerckhof** [comment]
@pixelass I haven't published it to atmosphere since it's very untested.
For now, just clone it and add it to the packages folder of a meteor project.

**Comment by pixelass** [comment]
```shell
cd [myMeteorProject]
git clone git@github.com:sebakerckhof/meteor-minifiers-autoprefix.git standard-minifiers
meteor add standard-minifiers
echo '{"autoprefixer":{"browsers":["last 2 versions"]}}' > .meteor/postcss.json
```

**Comment by pixelass** [comment]
seems to work as expected (no minifying though)

```css
prefixertest {
  display: flex;
  box-shadow: 0 0 0 red;
  user-select: none;
  
}
```

```css
prefixertest {
  display: -webkit-box;
  display: -webkit-flex;
  display: -ms-flexbox;
  display: flex;
  box-shadow: 0 0 0 red;
  -webkit-user-select: none;
     -moz-user-select: none;
      -ms-user-select: none;
          user-select: none;
}
```
