### ISSUE TITLE
invalid css quotes / Version "3.4.0-beta1" - no problem with 3.4.1

### ISSUE THREAD

**Issue by aheissenberger** [fourseven/meteor-scss#152]
This scss code with `#{data(`:
```scss
@function data($attr) {
  @return '[data-' + $attr + ']';
}

#{data('abidetest')} {
  display: block;
}
```
compiles to **BAD** - attribute selector should not be quoted:
```css
"[data-abidetest]" {
  display: block;
}
```

the correct result should be:
```css
[data-abidetest] {
  display: block;
}
```

I have tried with npm-sass@3.4.1 and this problem does not exist there
