### ISSUE TITLE
Installing autoprefix package breaks minifying stylesheets.

### ISSUE THREAD

**Issue by T-Grave** [fourseven/meteor-scss#164]
Hi,

I installed the recommended autoprefixer package, but it seems to break my build process.

After removing the standard-minifiers package and installing the new one I get this (meteor reset doesn't help either) and it has been doing this for minutes :/

Any ideas why this may be?

![image](https://cloud.githubusercontent.com/assets/7956579/12025255/fd61ff32-adac-11e5-956d-3e8be9c5896a.png)

**Comment by patrickml** [comment]
+1

**Comment by patrickml** [comment]
@T-Grave are you using flex box by chance? because if i remove my import for my grid which only has flex box in it it compiles

**Comment by patrickml** [comment]
@T-Grave changing to `flex` instead of `flex-box` fixed the issue for me

```scss
.flex-container {
  display : flex;
}

.col {
  padding : 7.5px;
}

.c-352 {
  width : 352px;
  flex-grow : 0;
}
.-c-352 {
  flex-grow : 1;
}
```
