### ISSUE TITLE
ability to set include paths

### ISSUE THREAD

**Issue by jasoncorbett** [fourseven/meteor-scss#175]
I'm trying to use ionic v2 (beta) and it needs the include paths part of the sass processing options set to include ionicons.  I don't like the way they did it, but in order for it to work I need to add an include path.  Can we set a config file in the root?  scssIncludePaths.json

**Comment by tensor5** [comment]
Same thing here. I'm trying to use bootstrap-sass and bootstrap-material-design with npm:

```
npm install --save bootstrap-sass bootstrap-material-design
```

in `main.scss`:
```scss
// Bootstrap
$icon-font-path: "/fonts/";
@import "{}/node_modules/bootstrap-sass/assets/stylesheets/bootstrap";

// Bootstrap Material Design
@import "{}/node_modules/bootstrap-material-design/sass/bootstrap-material-design";
@import "{}/node_modules/bootstrap-material-design/sass/ripples";
```

```
=> Errors prevented startup:                  
   
   While processing files with fourseven:scss (for target web.browser):
   /client/main.scss: Scss compiler error: File to import:
   {}/node_modules/bootstrap-material-design/sass/bootstrap/variables not found in
   file: _import-bs-sass
```

[` _import-bs-sass`](https://github.com/FezVrasta/bootstrap-material-design/blob/master/sass/_import-bs-sass.scss) requires a path from bootsrtap-sass relative to `{}/node_modules/bootstrap-sass/assets/stylesheets`, so it requires settings includePaths.
