### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Eruant** [fourseven/meteor-scss#79]
Would it be possible to add an extra step into the build process like you have do with autoprefixer?

The process is combining media queries. There are a few node modules out there that do this for you, and example of which is [gulp-combine-mq](https://www.npmjs.com/package/gulp-combine-mq).

Why? Well it's more efficient to have all of your media queries in one place, however when maintaining a large site it's easier to write these media queries in individual partials.

Here is an example of how I tend to write my queries (I also use [sass-mq](https://github.com/sass-mq/sass-mq), but that is our of scope here).

``` css
.parent {

  .child {
    width: 100%;

    @include mq($from: desktop) {
      width: 50%;
    }

    .another-child {
      background: hsl(0, 0, 25%);      

      @include mq($from: tablet) {
        width: 75%;
      }
    }
  }
}
```
